# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require(File.join(File.dirname(__FILE__), 'config', 'boot'))

require 'rake'
require 'rake/testtask'
require 'rake/rdoctask'

require 'tasks/rails'

REPORT_DIR = File.join(File.dirname(__FILE__), 'report')
STATUS_FILE = File.join(REPORT_DIR, 'status')

task :fluorida do
  execute 'mongrel_rails start -d'
  browser_cmd = '/cygdrive/c/Program\ Files/Internet\ Explorer/IEXPLORE.EXE http://localhost:3000/tester/open?suite=default.fls'
  mkdir_p REPORT_DIR
  File.open(STATUS_FILE, 'w'){|f| f.write 'testing'}
  browser = Thread.new{ execute browser_cmd } 

  while((status = File.open(STATUS_FILE){|f| f.read}) == 'testing') do
    sleep 1
  end

  browser.exit
  execute 'mongrel_rails stop'
  
  raise "Fluorida test failed!" unless status == 'successful'
end

def execute(cmd)
  puts cmd
  raise 'Execution error!' unless system cmd
end